# Chapter 6 Using Iteration (with_item) to install Multiple Packages
- name: Using Iteration (with_item) to install multiple packages
  hosts: all
#  sudo: True 這邊學到 sudo 不一定要放在一般選項內, 也可以放在 task 內
  tasks:
    - name: install yum packages
# 於 yum moudule 使用 sudo
      sudo: True
# 使用 pkg 加上 {{ item }} 配合後面的 with_item 來安裝多個套件
      yum: name={{ item }} 
# 配合前面的 {{ item }} 來安裝多套件
      with_items:
        - java-1.7.0-openjdk-devel
        - wget

    - name: Get scala
      shell: wget http://www.scala-lang.org/files/archive/scala-2.10.1.tgz

    - name: Exact source code of scala
      shell: tar xvf scala-2.10.1.tgz
      
    - name: Move scala to /usr/lib
      sudo: True
      shell: mv scala-2.10.1 /usr/lib
      
    - name: create link for scala
      sudo: True
      shell: ln -s /usr/lib/scala-2.10.1/  /usr/lib/scala
      
    - name: export $PATH to .bashrc
      lineinfile: dest=~/.bashrc line="export PATH=$PATH:/usr/lib/scala/bin"

# 由於沒有在 general option 使用 sudo, 這邊在使用 shell module 抓下來就是使用者自己的身份額非 root
    - name: Download spark with pre-build hadoop
      shell: wget    http://archive.apache.org/dist/spark/spark-1.4.0/spark-1.4.0-bin-hadoop2.6.tgz

# 解開 source code
    - name: Exact pre-build source
      shell: tar zxvf spark-*.tgz

    - name: Rename spark folder
      shell: mv ~/spark*/ ~/spark


# 測試 jps 指令
    - name: Testing jps command
      command: jps
      register: jps
    - debug: var=jps.stdout_lines
